/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/waterbottle-v1.glb --transform 
Files: public/waterbottle-v1.glb [542.16KB] > C:\Users\ruims\Projects\Water Bottle\waterbottle-v1-transformed.glb [76.6KB] (86%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Bottle(props) {
    const { nodes, materials } = useGLTF('/waterbottle-v1-transformed.glb')
    return (
        <group {...props} dispose={null}>
            <mesh
                geometry={nodes.Object_6.geometry}
                material={materials['Material.003']}
                position={[0, 4.186, 0.012]}
                scale={[0.268, 0.193, 0.268]}
            />
            <mesh
                geometry={nodes.Object_8.geometry}
                material={materials['Material.004']}
                position={[0, 0.692, 0.011]}
                scale={0.672}
            />
            <mesh
                geometry={nodes.Object_4.geometry}
                material={materials['Material.002']}
                position={[0, 0.692, 0.011]}
                scale={0.69}
            />
        </group>
    )
}

useGLTF.preload('/waterbottle-v1-transformed.glb')
